### PR TITLE
Fix compilation and deprecated libraries

### PR DESCRIPTION
**Pull request by kedio**
I just happen to try the simple-chat-swift app and struggled to get "text to speech" working. So I figured I should share my solution for anyone stumbling on the same problem.

### CODE REVIEW

**Review by germanattanasio — APPROVED** [review]

**Comment by germanattanasio** [comment]
@kedio your commits don't get associated with your GitHub account. Make sure you configure your identity in git. See [this](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) tutorial

**Review by glennrfisher — APPROVED** [review]
Thanks for the updates, @kedio!

**Comment by germanattanasio** [comment]
I'm going to let @glennrfisher review this

**Comment by kedio** [comment]
@germanattanasio thank you for the heads up, this is a new computer and I forgot to update my config!

**Pull request merged**
